[build]
  publish = "dist"
  command = "npm run build"

[forms]
  [forms.contact]
    name = "contact"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"